#!/bin/bash
last=10029

LAST=${1:-${last}}
cd /sources/svn/freevo-1/rel-1-7
echo "last change is: ${LAST}"
svn merge -r${LAST}:HEAD /sources/svn/freevo-1/rel-1 . --dry-run
echo "press enter to do it"
read ENTER
svn merge -r${LAST}:HEAD /sources/svn/freevo-1/rel-1 .
